export const ADD_EMPLOYEE="ADD_EMPLOYEE"
export const GET_EMPLOYEE_START="GET_EMPLOYEE_START"
export const GET_EMPLOYEE_SUCCESS="GET_EMPLOYEE_SUCCESS"

export const GET_EMPLOYEE_FAIL="GET_EMPLOYEE_FAIL"
export const DELETE_EMPLOYEE_SUCCESS="DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_START="DELETE_EMPLOYEE_START"
export const DELETE_EMPLOYEE_FAIL="DELETE_EMPLOYEE_FAIL"
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE"

export const POST_EMPLOYEE_SUCCESS="POST_EMPLOYEE_SUCCESS"
export const POST_EMPLOYEE_START="POST_EMPLOYEE_START"
export const POST_EMPLOYEE_FAIL="POST_EMPLOYEE_SUCCESS"